apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: jenkins-cert
spec:
  secretName: jenkins-cert
  commonName: jenkins.kwk8s.tech
  dnsNames:
  - jenkins.kwk8s.tech
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer