apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
        - name: jenkins
          image: kristianwindsor/jenkins
          ports:
            - containerPort: 8080
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: KUBE_URL
              value: 54.153.89.181:6443
            - name: KUBE_CA
              valueFrom:
                secretKeyRef:
                  name: jenkins-env
                  key: KUBE_CA
            - name: KUBE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jenkins-env
                  key: KUBE_TOKEN
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "/postStart.sh"]
          resources:
            requests:
              memory: "320Mi"
              cpu: "160m"
            limits:
              memory: "640Mi"
              cpu: "320m"
          volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home/
        - name: docker
          image: docker:18.09.8-dind
          ports:
            - containerPort: 2375
          resources:
            requests:
              memory: "160Mi"
              cpu: "80m"
            limits:
              memory: "320Mi"
              cpu: "160m"
          securityContext:
            privileged: true
      volumes:
        - name: jenkins-storage
          persistentVolumeClaim:
            claimName: jenkins-storage
      securityContext:
        runAsUser: 0
